[package]
name = "tracing_publisher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
kafka = "0.9.0"
serde_json = "1.0.93"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
